# Generated by Django 5.1.3 on 2024-11-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='tweet/'),
        ),
    ]
